// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEebsdbtv5IGNQ4ptQ0LwliU8IZgLCw1o',
    appId: '1:1052171015068:web:7d26cef4cce2bbf88aae59',
    messagingSenderId: '1052171015068',
    projectId: 'utilwise-6e819',
    authDomain: 'utilwise-6e819.firebaseapp.com',
    storageBucket: 'utilwise-6e819.firebasestorage.app',
    measurementId: 'G-LXT39GY9F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfZ3iSOO67SgMm1s4rCBN0_LBRVPllw40',
    appId: '1:1052171015068:android:5af837255abdfe048aae59',
    messagingSenderId: '1052171015068',
    projectId: 'utilwise-6e819',
    storageBucket: 'utilwise-6e819.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx5B-t3ABlwm0-pWimKBzDYDTzUdlu9Xw',
    appId: '1:1052171015068:ios:b9c9ee8ecc5f5da48aae59',
    messagingSenderId: '1052171015068',
    projectId: 'utilwise-6e819',
    storageBucket: 'utilwise-6e819.firebasestorage.app',
    iosBundleId: 'com.example.utilwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx5B-t3ABlwm0-pWimKBzDYDTzUdlu9Xw',
    appId: '1:1052171015068:ios:b9c9ee8ecc5f5da48aae59',
    messagingSenderId: '1052171015068',
    projectId: 'utilwise-6e819',
    storageBucket: 'utilwise-6e819.firebasestorage.app',
    iosBundleId: 'com.example.utilwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEebsdbtv5IGNQ4ptQ0LwliU8IZgLCw1o',
    appId: '1:1052171015068:web:7583e8a1c32951d88aae59',
    messagingSenderId: '1052171015068',
    projectId: 'utilwise-6e819',
    authDomain: 'utilwise-6e819.firebaseapp.com',
    storageBucket: 'utilwise-6e819.firebasestorage.app',
    measurementId: 'G-9PT3EYRTG0',
  );

}